'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.8009
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class ErrorsAPI
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("domDNS.ErrorsAPI", GetType(ErrorsAPI).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El dominio seleccionado ya no está activo..
        '''</summary>
        Friend Shared ReadOnly Property DOMINIO_INACTIVO() As String
            Get
                Return ResourceManager.GetString("DOMINIO_INACTIVO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ha ocurrido un error accediendo a la base de datos.
        '''Si el problema continúa ponte en contacto con soporte técnico..
        '''</summary>
        Friend Shared ReadOnly Property ERROR_DINAHOSTING_CANT_ANSWER() As String
            Get
                Return ResourceManager.GetString("ERROR_DINAHOSTING_CANT_ANSWER", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La combinación del usuario y la contraseña no son válidos.
        '''Asegúrate de que son correctos y que se corresponden con el usuario de dinahosting o el dominio..
        '''</summary>
        Friend Shared ReadOnly Property ERROR_FAILED_LOGIN() As String
            Get
                Return ResourceManager.GetString("ERROR_FAILED_LOGIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Es necesario un valor para la dirección..
        '''</summary>
        Friend Shared ReadOnly Property ERROR_LACKS_ADDRESS_() As String
            Get
                Return ResourceManager.GetString("ERROR_LACKS_ADDRESS_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Es necesario un valor para la zona..
        '''</summary>
        Friend Shared ReadOnly Property ERROR_LACKS_HOST_() As String
            Get
                Return ResourceManager.GetString("ERROR_LACKS_HOST_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No se tradujo porque nunca se daba..
        '''</summary>
        Friend Shared ReadOnly Property ERROR_LACKS_TYPE_() As String
            Get
                Return ResourceManager.GetString("ERROR_LACKS_TYPE_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No es posible configurar un CNAME del registro @..
        '''</summary>
        Friend Shared ReadOnly Property ERROR_WRONG_CNAMESPECIAL_() As String
            Get
                Return ResourceManager.GetString("ERROR_WRONG_CNAMESPECIAL_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Un CNAME debe apuntar a otro host o a un nombre de dominio acabado en &apos;.&apos;.
        '''</summary>
        Friend Shared ReadOnly Property ERROR_WRONG_FQDN_() As String
            Get
                Return ResourceManager.GetString("ERROR_WRONG_FQDN_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Host no válido..
        '''</summary>
        Friend Shared ReadOnly Property ERROR_WRONG_HOST_() As String
            Get
                Return ResourceManager.GetString("ERROR_WRONG_HOST_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Los MX deben ser distintos..
        '''</summary>
        Friend Shared ReadOnly Property ERROR_WRONG_IGUALES_() As String
            Get
                Return ResourceManager.GetString("ERROR_WRONG_IGUALES_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a IP no válida..
        '''</summary>
        Friend Shared ReadOnly Property ERROR_WRONG_IP_() As String
            Get
                Return ResourceManager.GetString("ERROR_WRONG_IP_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El MX tiene que tener su zona definida..
        '''</summary>
        Friend Shared ReadOnly Property ERROR_WRONG_NODEFINIDO_() As String
            Get
                Return ResourceManager.GetString("ERROR_WRONG_NODEFINIDO_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El tipo de la zona no es correcto..
        '''</summary>
        Friend Shared ReadOnly Property ERROR_WRONG_TYPE_() As String
            Get
                Return ResourceManager.GetString("ERROR_WRONG_TYPE_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a URL no válida.
        '''</summary>
        Friend Shared ReadOnly Property ERROR_WRONG_URL_() As String
            Get
                Return ResourceManager.GetString("ERROR_WRONG_URL_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Zonas definidas. Error de comunicación con el registro para
        '''establecer DNS&apos;s adecuadas. Inténtalo más tarde..
        '''</summary>
        Friend Shared ReadOnly Property REGISTRADOR_CAIDO() As String
            Get
                Return ResourceManager.GetString("REGISTRADOR_CAIDO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Alguna IP introducida no es válida..
        '''</summary>
        Friend Shared ReadOnly Property WRONGIP_() As String
            Get
                Return ResourceManager.GetString("WRONGIP_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Alguna MX introducida no es válido..
        '''</summary>
        Friend Shared ReadOnly Property WRONGMX_() As String
            Get
                Return ResourceManager.GetString("WRONGMX_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Debes seleccionar una de las opciones..
        '''</summary>
        Friend Shared ReadOnly Property WRONGRULE_() As String
            Get
                Return ResourceManager.GetString("WRONGRULE_", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
